// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Ipsp6_cPU4wYrqKjw9_i6ydfuMNc3lY',
    appId: '1:334523270436:web:3bf32cd792722ce5ba5fb1',
    messagingSenderId: '334523270436',
    projectId: 'dentalprogapplication',
    authDomain: 'dentalprogapplication.firebaseapp.com',
    storageBucket: 'dentalprogapplication.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW0ko8mOgmRzkdcous-bEX6hboDBWEMxo',
    appId: '1:334523270436:android:7ba09f28a8dbcfdfba5fb1',
    messagingSenderId: '334523270436',
    projectId: 'dentalprogapplication',
    storageBucket: 'dentalprogapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChwWsIgDbD4EDLlqm9S6q6qaPgEoCwIPk',
    appId: '1:334523270436:ios:82a89216649d50c5ba5fb1',
    messagingSenderId: '334523270436',
    projectId: 'dentalprogapplication',
    storageBucket: 'dentalprogapplication.appspot.com',
    iosBundleId: 'com.example.dentalprogapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChwWsIgDbD4EDLlqm9S6q6qaPgEoCwIPk',
    appId: '1:334523270436:ios:189c31f089bdb2f0ba5fb1',
    messagingSenderId: '334523270436',
    projectId: 'dentalprogapplication',
    storageBucket: 'dentalprogapplication.appspot.com',
    iosBundleId: 'com.example.dentalprogapplication.RunnerTests',
  );
}
